// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Sum_and_nullableIsAccepted : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sum_and_nullableIsAccepted));
        
        string IMigrationMetadata.Id
        {
            get { return "201808090736301_Sum_and_nullableIsAccepted"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
